name: hakkason_team_h
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter_riverpod: ^2.3.6
  flutter:
    sdk: flutter
  shadcn_flutter: ^0.0.44
  table_calendar: ^3.2.0
  intl: ^0.20.2
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
